version: '3.2'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - redis
      - db
    environment:
      RAILS_ENV: 'production'
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_SERVE_STATIC_FILES: 'true'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - type: bind
        source: ./
        target: /application
        consistency: delegated
  # php:
  #   build:
  #     context: ../timetable-php
  #     dockerfile: Dockerfile
  #   volumes:
  #     - type: bind
  #       source: ../timetable-php
  #       target: /var/www/html
  #       consistency: delegated
  #   ports:
  #     - "3000:80"
  #   environment:
  #     DEBUG: 0
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/mysql
        consistency: cached
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: 'timetable'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'