version: '3'
services:
  api:
    image: "vbhjckfd/timetable-api"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
    ports:
     - "80:80"
  # fe:
  #   image: "vbhjckfd/timetable-fe"
  #   environment:
  #     - API_URL=http://api/
  #   ports:
  #    - "82:4567"
