FROM docker.io/ruby:2.6.2-alpine3.9

RUN apk update && apk add --no-cache git build-base sqlite-dev curl

RUN bundle config --global frozen 1

COPY Gemfile Gemfile.lock /application/

# Change to the application's directory
WORKDIR /application

RUN bundle install --deployment --without development test

COPY . /application/

EXPOSE 80

ENTRYPOINT ["./entrypoint.sh"]
